"""описание изменений

Revision ID: a08ccca1e81c
Revises: 6af5c7d22f12
Create Date: 2025-05-11 14:03:12.429696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08ccca1e81c'
down_revision: Union[str, None] = '6af5c7d22f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('draws', sa.Column('cycle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'draws', 'cycles', ['cycle_id'], ['id'])
    op.add_column('participants', sa.Column('frequency_individual', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'frequency_individual')
    op.drop_constraint(None, 'draws', type_='foreignkey')
    op.drop_column('draws', 'cycle_id')
    op.drop_table('cycles')
    # ### end Alembic commands ###
