"""initial

Revision ID: cef9a0f73ed0
Revises: d399d94b5de8
Create Date: 2025-05-11 14:14:09.610279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef9a0f73ed0'
down_revision: Union[str, None] = 'd399d94b5de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('frequency_individual', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('exclude_start', sa.Date(), nullable=True),
    sa.Column('exclude_end', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('frequency_in_weeks', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_id', sa.Integer(), nullable=True),
    sa.Column('participant1_id', sa.Integer(), nullable=True),
    sa.Column('participant2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['draw_id'], ['draws.id'], ),
    sa.ForeignKeyConstraint(['participant1_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['participant2_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pairs')
    op.drop_table('draws')
    op.drop_table('settings')
    op.drop_table('participants')
    op.drop_table('cycles')
    # ### end Alembic commands ###
